### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by krishnamrith12** [shyamupa/hma-translit#2]
Hi, The current links for Kannada and Hindi aren't available. It would be helpful if you can share the same

**Comment by VrutikShah** [comment]
Same issue. It would help if you could provide updated links to those datasets

**Comment by shyamupa** [comment]
There is some misunderstanding. I have never posted links to the NEWS dataset in my repo. You have to reach out to the NEWS task organizers to get the data.
